import { Model, Element, AnalysisResult } from '@/types/rfem';

export const mockModels: Model[] = [
  { id: 'model-1', name: 'Tower Crane Foundation', updated_at: '2025-01-15T10:30:00Z' },
  { id: 'model-2', name: 'Main Building Frame', updated_at: '2025-01-14T15:45:00Z' },
  { id: 'model-3', name: 'Bridge Deck Analysis', updated_at: '2025-01-13T09:20:00Z' },
];

// Model-specific elements
export const mockElementsByModel: Record<string, Element[]> = {
  'model-1': [
    { id: 123, label: 'Column L1-NW', type: 'COLUMN' },
    { id: 234, label: 'Column L1-NE', type: 'COLUMN' },
    { id: 345, label: 'Column L1-SW', type: 'COLUMN' },
    { id: 456, label: 'Column L1-SE', type: 'COLUMN' },
    { id: 124, label: 'Column L2-NW', type: 'COLUMN' },
    { id: 235, label: 'Column L2-NE', type: 'COLUMN' },
    { id: 346, label: 'Column L2-SW', type: 'COLUMN' },
    { id: 457, label: 'Column L2-SE', type: 'COLUMN' },
    { id: 125, label: 'Column L3-NW', type: 'COLUMN' },
    { id: 236, label: 'Column L3-NE', type: 'COLUMN' },
    { id: 347, label: 'Column L3-SW', type: 'COLUMN' },
    { id: 458, label: 'Column L3-SE', type: 'COLUMN' },
    { id: 451, label: 'Beam L1-North', type: 'BEAM' },
    { id: 567, label: 'Beam L1-South', type: 'BEAM' },
    { id: 678, label: 'Beam L1-West', type: 'BEAM' },
    { id: 789, label: 'Beam L1-East', type: 'BEAM' },
    { id: 452, label: 'Beam L2-North', type: 'BEAM' },
    { id: 568, label: 'Beam L2-South', type: 'BEAM' },
    { id: 679, label: 'Beam L2-West', type: 'BEAM' },
    { id: 790, label: 'Beam L2-East', type: 'BEAM' },
    { id: 453, label: 'Beam L3-North', type: 'BEAM' },
    { id: 569, label: 'Beam L3-South', type: 'BEAM' },
    { id: 680, label: 'Beam L3-West', type: 'BEAM' },
    { id: 791, label: 'Beam L3-East', type: 'BEAM' },
    { id: 782, label: 'Brace L1-N-X1', type: 'TRUSS' },
    { id: 890, label: 'Brace L1-N-X2', type: 'TRUSS' },
    { id: 891, label: 'Brace L1-S-X1', type: 'TRUSS' },
    { id: 892, label: 'Brace L1-S-X2', type: 'TRUSS' },
    { id: 893, label: 'Brace L1-W-Y1', type: 'TRUSS' },
    { id: 894, label: 'Brace L1-W-Y2', type: 'TRUSS' },
    { id: 895, label: 'Brace L1-E-Y1', type: 'TRUSS' },
    { id: 896, label: 'Brace L1-E-Y2', type: 'TRUSS' },
    { id: 783, label: 'Brace L2-N-X1', type: 'TRUSS' },
    { id: 897, label: 'Brace L2-N-X2', type: 'TRUSS' },
    { id: 898, label: 'Brace L2-S-X1', type: 'TRUSS' },
    { id: 899, label: 'Brace L2-S-X2', type: 'TRUSS' },
    { id: 784, label: 'Brace L3-N-X1', type: 'TRUSS' },
    { id: 900, label: 'Brace L3-N-X2', type: 'TRUSS' },
  ],
  'model-2': [
    { id: 101, label: 'Ground A1', type: 'COLUMN' },
    { id: 102, label: 'Ground A2', type: 'COLUMN' },
    { id: 103, label: 'Ground A3', type: 'COLUMN' },
    { id: 104, label: 'Ground A4', type: 'COLUMN' },
    { id: 105, label: 'Ground B1', type: 'COLUMN' },
    { id: 106, label: 'Ground B2', type: 'COLUMN' },
    { id: 107, label: 'Ground B3', type: 'COLUMN' },
    { id: 108, label: 'Ground B4', type: 'COLUMN' },
    { id: 109, label: 'Ground C1', type: 'COLUMN' },
    { id: 110, label: 'Ground C2', type: 'COLUMN' },
    { id: 111, label: 'Ground C3', type: 'COLUMN' },
    { id: 112, label: 'Ground C4', type: 'COLUMN' },
    { id: 113, label: 'Ground D1', type: 'COLUMN' },
    { id: 114, label: 'Ground D2', type: 'COLUMN' },
    { id: 115, label: 'Ground D3', type: 'COLUMN' },
    { id: 116, label: 'Ground D4', type: 'COLUMN' },
    { id: 201, label: 'Floor2 A1', type: 'COLUMN' },
    { id: 202, label: 'Floor2 A2', type: 'COLUMN' },
    { id: 203, label: 'Floor2 A3', type: 'COLUMN' },
    { id: 204, label: 'Floor2 A4', type: 'COLUMN' },
    { id: 205, label: 'Floor2 C1', type: 'COLUMN' },
    { id: 206, label: 'Floor2 C4', type: 'COLUMN' },
    { id: 301, label: 'Floor3 A1', type: 'COLUMN' },
    { id: 302, label: 'Floor3 A3', type: 'COLUMN' },
    { id: 303, label: 'Floor3 A4', type: 'COLUMN' },
    { id: 351, label: 'Floor4 A1', type: 'COLUMN' },
    { id: 352, label: 'Floor4 A4', type: 'COLUMN' },
    { id: 401, label: 'Beam 1-A12', type: 'BEAM' },
    { id: 402, label: 'Beam 1-A23', type: 'BEAM' },
    { id: 403, label: 'Beam 1-A34', type: 'BEAM' },
    { id: 404, label: 'Beam 1-B12', type: 'BEAM' },
    { id: 405, label: 'Beam 1-B23', type: 'BEAM' },
    { id: 406, label: 'Beam 1-B34', type: 'BEAM' },
    { id: 411, label: 'Beam 1-1AB', type: 'BEAM' },
    { id: 412, label: 'Beam 1-1BC', type: 'BEAM' },
    { id: 413, label: 'Beam 1-1CD', type: 'BEAM' },
    { id: 414, label: 'Beam 1-4AB', type: 'BEAM' },
    { id: 501, label: 'Beam 2-A12', type: 'BEAM' },
    { id: 502, label: 'Beam 2-A23', type: 'BEAM' },
    { id: 503, label: 'Beam 2-A34', type: 'BEAM' },
    { id: 504, label: 'Beam 2-1C', type: 'BEAM' },
    { id: 601, label: 'Beam 3-A13', type: 'BEAM' },
    { id: 602, label: 'Beam 3-A34', type: 'BEAM' },
    { id: 701, label: 'Beam 4-A14', type: 'BEAM' },
    { id: 801, label: 'Brace 1-A1', type: 'TRUSS' },
    { id: 802, label: 'Brace 1-A2', type: 'TRUSS' },
    { id: 803, label: 'Brace 1-A3', type: 'TRUSS' },
    { id: 804, label: 'Brace 1-1A', type: 'TRUSS' },
    { id: 805, label: 'Brace 1-1B', type: 'TRUSS' },
    { id: 811, label: 'Brace 2-A1', type: 'TRUSS' },
    { id: 812, label: 'Brace 2-A2', type: 'TRUSS' },
    { id: 813, label: 'Brace 2-A3', type: 'TRUSS' },
  ],
  'model-3': [
    { id: 501, label: 'Pier P-1', type: 'COLUMN' },
    { id: 502, label: 'Pier P-2', type: 'COLUMN' },
    { id: 503, label: 'Pier P-3', type: 'COLUMN' },
    { id: 504, label: 'Pier P-4', type: 'COLUMN' },
    { id: 505, label: 'Pier P-5', type: 'COLUMN' },
    { id: 506, label: 'Pier P-6', type: 'COLUMN' },
    { id: 507, label: 'Tower South', type: 'COLUMN' },
    { id: 508, label: 'Tower North', type: 'COLUMN' },
    { id: 601, label: 'Main Span 1-2', type: 'BEAM' },
    { id: 602, label: 'Main Span 2-3', type: 'BEAM' },
    { id: 603, label: 'Main Span 3-4', type: 'BEAM' },
    { id: 604, label: 'Main Span 4-5', type: 'BEAM' },
    { id: 605, label: 'Main Span 5-6', type: 'BEAM' },
    { id: 606, label: 'Side Beam 1-2R', type: 'BEAM' },
    { id: 607, label: 'Side Beam 2-3R', type: 'BEAM' },
    { id: 608, label: 'Side Beam 3-4R', type: 'BEAM' },
    { id: 609, label: 'Side Beam 4-5R', type: 'BEAM' },
    { id: 610, label: 'Side Beam 5-6R', type: 'BEAM' },
    { id: 611, label: 'Side Beam 1-2L', type: 'BEAM' },
    { id: 612, label: 'Side Beam 2-3L', type: 'BEAM' },
    { id: 613, label: 'Side Beam 3-4L', type: 'BEAM' },
    { id: 614, label: 'Side Beam 4-5L', type: 'BEAM' },
    { id: 615, label: 'Side Beam 5-6L', type: 'BEAM' },
    { id: 701, label: 'Truss T1-A', type: 'TRUSS' },
    { id: 702, label: 'Truss T2-A', type: 'TRUSS' },
    { id: 703, label: 'Truss T3-A', type: 'TRUSS' },
    { id: 704, label: 'Truss T4-A', type: 'TRUSS' },
    { id: 705, label: 'Truss T5-A', type: 'TRUSS' },
    { id: 706, label: 'Truss T1-B', type: 'TRUSS' },
    { id: 707, label: 'Truss T2-B', type: 'TRUSS' },
    { id: 708, label: 'Truss T3-B', type: 'TRUSS' },
    { id: 709, label: 'Truss T4-B', type: 'TRUSS' },
    { id: 710, label: 'Truss T5-B', type: 'TRUSS' },
    { id: 711, label: 'Cable Stay S1', type: 'TRUSS' },
    { id: 712, label: 'Cable Stay S2', type: 'TRUSS' },
    { id: 713, label: 'Cable Stay S3', type: 'TRUSS' },
    { id: 714, label: 'Cable Stay N1', type: 'TRUSS' },
    { id: 715, label: 'Cable Stay N2', type: 'TRUSS' },
    { id: 716, label: 'Cable Stay N3', type: 'TRUSS' },
    { id: 720, label: 'Lateral Brace 1', type: 'TRUSS' },
    { id: 721, label: 'Lateral Brace 2', type: 'TRUSS' },
    { id: 722, label: 'Lateral Brace 3', type: 'TRUSS' },
    { id: 723, label: 'Lateral Brace 4', type: 'TRUSS' },
    { id: 724, label: 'Lateral Brace 5', type: 'TRUSS' },
  ],
};

export const mockElements = mockElementsByModel['model-1'];

// Model-specific analysis results
export const mockAnalysisResultsByModel: Record<string, AnalysisResult> = {
  'model-1': {
    status: 'succeeded',
    summary: {
      max_util: 1.03,
      max_defl_mm: 24,
      exceed_count: 2,
    },
    exceedances: [
      {
        element_id: 123,
        type: 'utilization',
        value: 1.03,
        limit: 0.95,
        location: 'Northwest Corner',
        recommendation: 'Stop lift; add temporary shore',
      },
      {
        element_id: 451,
        type: 'deflection_mm',
        value: 24,
        limit: 20,
        location: 'North Beam',
        recommendation: 'Reduce load by 10%',
      },
    ],
    heatmap: [
      { element_id: 123, util: 1.03 },
      { element_id: 234, util: 0.65 },
      { element_id: 345, util: 0.58 },
      { element_id: 456, util: 0.62 },
      { element_id: 124, util: 0.78 },
      { element_id: 235, util: 0.54 },
      { element_id: 346, util: 0.51 },
      { element_id: 457, util: 0.59 },
      { element_id: 125, util: 0.48 },
      { element_id: 236, util: 0.43 },
      { element_id: 347, util: 0.39 },
      { element_id: 458, util: 0.44 },
      { element_id: 451, util: 0.88 },
      { element_id: 567, util: 0.91 },
      { element_id: 678, util: 0.45 },
      { element_id: 789, util: 0.52 },
      { element_id: 452, util: 0.76 },
      { element_id: 568, util: 0.82 },
      { element_id: 679, util: 0.41 },
      { element_id: 790, util: 0.47 },
      { element_id: 782, util: 0.72 },
      { element_id: 890, util: 0.68 },
      { element_id: 891, util: 0.64 },
      { element_id: 892, util: 0.61 },
      { element_id: 893, util: 0.55 },
      { element_id: 894, util: 0.58 },
      { element_id: 783, util: 0.66 },
      { element_id: 897, util: 0.63 },
    ],
    report_url: 'https://rfem-backend.example.com/reports/tower-crane.pdf',
  },
  'model-2': {
    status: 'succeeded',
    summary: {
      max_util: 0.94,
      max_defl_mm: 18,
      exceed_count: 0,
    },
    exceedances: [],
    heatmap: [
      { element_id: 101, util: 0.82 },
      { element_id: 102, util: 0.89 },
      { element_id: 103, util: 0.76 },
      { element_id: 104, util: 0.78 },
      { element_id: 105, util: 0.94 },
      { element_id: 106, util: 0.71 },
      { element_id: 107, util: 0.73 },
      { element_id: 108, util: 0.85 },
      { element_id: 109, util: 0.68 },
      { element_id: 110, util: 0.77 },
      { element_id: 111, util: 0.81 },
      { element_id: 112, util: 0.74 },
      { element_id: 201, util: 0.68 },
      { element_id: 202, util: 0.75 },
      { element_id: 203, util: 0.64 },
      { element_id: 204, util: 0.71 },
      { element_id: 205, util: 0.69 },
      { element_id: 206, util: 0.66 },
      { element_id: 301, util: 0.58 },
      { element_id: 302, util: 0.61 },
      { element_id: 303, util: 0.55 },
      { element_id: 401, util: 0.85 },
      { element_id: 402, util: 0.88 },
      { element_id: 403, util: 0.79 },
      { element_id: 404, util: 0.81 },
      { element_id: 405, util: 0.76 },
      { element_id: 406, util: 0.83 },
      { element_id: 501, util: 0.72 },
      { element_id: 502, util: 0.68 },
      { element_id: 503, util: 0.74 },
      { element_id: 601, util: 0.58 },
      { element_id: 602, util: 0.62 },
      { element_id: 801, util: 0.54 },
      { element_id: 802, util: 0.51 },
      { element_id: 803, util: 0.56 },
      { element_id: 811, util: 0.48 },
      { element_id: 812, util: 0.45 },
    ],
    report_url: 'https://rfem-backend.example.com/reports/building-frame.pdf',
  },
  'model-3': {
    status: 'succeeded',
    summary: {
      max_util: 0.98,
      max_defl_mm: 32,
      exceed_count: 3,
    },
    exceedances: [
      {
        element_id: 602,
        type: 'deflection_mm',
        value: 32,
        limit: 20,
        location: 'Span 2-3 Midpoint',
        recommendation: 'Install additional support at midspan',
      },
      {
        element_id: 603,
        type: 'utilization',
        value: 0.98,
        limit: 0.95,
        location: 'Span 3-4',
        recommendation: 'Reduce live load or upgrade section',
      },
      {
        element_id: 503,
        type: 'utilization',
        value: 0.96,
        limit: 0.95,
        location: 'Center Pier',
        recommendation: 'Monitor closely during peak loads',
      },
    ],
    heatmap: [
      { element_id: 501, util: 0.74 },
      { element_id: 502, util: 0.88 },
      { element_id: 503, util: 0.96 },
      { element_id: 504, util: 0.85 },
      { element_id: 505, util: 0.72 },
      { element_id: 506, util: 0.69 },
      { element_id: 507, util: 0.91 },
      { element_id: 508, util: 0.89 },
      { element_id: 601, util: 0.81 },
      { element_id: 602, util: 0.93 },
      { element_id: 603, util: 0.98 },
      { element_id: 604, util: 0.79 },
      { element_id: 605, util: 0.76 },
      { element_id: 606, util: 0.73 },
      { element_id: 607, util: 0.84 },
      { element_id: 608, util: 0.87 },
      { element_id: 609, util: 0.71 },
      { element_id: 610, util: 0.68 },
      { element_id: 701, util: 0.65 },
      { element_id: 702, util: 0.71 },
      { element_id: 703, util: 0.68 },
      { element_id: 704, util: 0.62 },
      { element_id: 705, util: 0.58 },
      { element_id: 706, util: 0.64 },
      { element_id: 707, util: 0.61 },
      { element_id: 708, util: 0.57 },
      { element_id: 709, util: 0.59 },
      { element_id: 710, util: 0.55 },
      { element_id: 711, util: 0.82 },
      { element_id: 712, util: 0.78 },
      { element_id: 713, util: 0.74 },
      { element_id: 714, util: 0.81 },
      { element_id: 715, util: 0.77 },
      { element_id: 716, util: 0.73 },
      { element_id: 720, util: 0.52 },
      { element_id: 721, util: 0.56 },
      { element_id: 722, util: 0.54 },
      { element_id: 723, util: 0.51 },
      { element_id: 724, util: 0.49 },
    ],
    report_url: 'https://rfem-backend.example.com/reports/bridge-deck.pdf',
  },
};

export const mockAnalysisResult = mockAnalysisResultsByModel['model-1'];

export const generateMockProgress = () => {
  const steps = [
    { progress: 0.1, message: 'Initializing analysis...' },
    { progress: 0.25, message: 'Assembling model...' },
    { progress: 0.5, message: 'Applying loads...' },
    { progress: 0.75, message: 'Running calculations...' },
    { progress: 0.9, message: 'Generating results...' },
    { progress: 1.0, message: 'Analysis complete' },
  ];
  return steps;
};
