import { Download, FileText, Printer } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Exceedance, AnalysisResult } from '@/types/rfem';
import { useToast } from '@/hooks/use-toast';

interface ReportsTabProps {
  reportUrl?: string;
  exceedances?: Exceedance[];
  analysisResult?: AnalysisResult;
  modelName?: string;
}

export function ReportsTab({ reportUrl, exceedances, analysisResult, modelName }: ReportsTabProps) {
  const { toast } = useToast();

  const handlePrintReport = () => {
    if (!analysisResult) return;
    
    // Open print dialog with formatted report
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      toast({
        title: 'Pop-up Blocked',
        description: 'Please allow pop-ups to generate the report',
        variant: 'destructive',
      });
      return;
    }

    const reportHTML = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Analysis Report - ${modelName || 'Model'}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; }
            h1 { color: #1a1a1a; border-bottom: 3px solid #333; padding-bottom: 10px; }
            h2 { color: #333; margin-top: 30px; border-bottom: 1px solid #ddd; padding-bottom: 5px; }
            .summary-box { background: #f5f5f5; padding: 20px; border-radius: 8px; margin: 20px 0; }
            .critical { color: #dc2626; font-weight: bold; }
            .warning { color: #ea580c; font-weight: bold; }
            .safe { color: #16a34a; font-weight: bold; }
            .exceedance { margin: 15px 0; padding: 15px; border-left: 4px solid #dc2626; background: #fef2f2; }
            table { width: 100%; border-collapse: collapse; margin: 20px 0; }
            th, td { padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }
            th { background: #333; color: white; }
            .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-size: 12px; }
          </style>
        </head>
        <body>
          <h1>Structural Analysis Report</h1>
          
          <div class="summary-box">
            <p><strong>Model:</strong> ${modelName || 'Unknown Model'}</p>
            <p><strong>Analysis Date:</strong> ${new Date().toLocaleDateString()}</p>
            <p><strong>Status:</strong> ${analysisResult.status.toUpperCase()}</p>
          </div>

          ${analysisResult.summary ? `
            <h2>Analysis Summary</h2>
            <table>
              <tr>
                <th>Metric</th>
                <th>Value</th>
              </tr>
              <tr>
                <td>Maximum Utilization</td>
                <td>${(analysisResult.summary.max_util * 100).toFixed(1)}%</td>
              </tr>
              <tr>
                <td>Maximum Deflection</td>
                <td>${analysisResult.summary.max_defl_mm.toFixed(2)} mm</td>
              </tr>
              <tr>
                <td>Elements Exceeding Limits</td>
                <td>${analysisResult.summary.exceed_count}</td>
              </tr>
            </table>
            
            <div class="summary-box ${analysisResult.summary.max_util >= 0.95 ? 'critical' : analysisResult.summary.max_util >= 0.85 ? 'warning' : 'safe'}">
              ${analysisResult.summary.max_util >= 0.95 
                ? '⚠ CRITICAL: Immediate action required' 
                : analysisResult.summary.max_util >= 0.85 
                ? '⚠ WARNING: High utilization detected' 
                : '✓ SAFE: All elements within limits'}
            </div>
          ` : ''}

          ${analysisResult.exceedances && analysisResult.exceedances.length > 0 ? `
            <h2>Exceedances & Recommendations</h2>
            ${analysisResult.exceedances.map((exc, index) => `
              <div class="exceedance">
                <h3>Element ${exc.element_id} - ${exc.type}</h3>
                <p><strong>Location:</strong> ${exc.location}</p>
                <p><strong>Value:</strong> ${exc.value.toFixed(2)} | <strong>Limit:</strong> ${exc.limit.toFixed(2)}</p>
                <p><strong>Recommendation:</strong> ${exc.recommendation}</p>
              </div>
            `).join('')}
          ` : ''}

          <div class="footer">
            <p>Generated by RFEM Analysis System on ${new Date().toLocaleString()}</p>
          </div>
        </body>
      </html>
    `;

    printWindow.document.write(reportHTML);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 250);

    toast({ title: 'Report Ready', description: 'Print dialog opened' });
  };

  const exportToCSV = () => {
    if (!exceedances || exceedances.length === 0) return;

    const headers = ['Element ID', 'Type', 'Value', 'Limit', 'Location', 'Recommendation'];
    const rows = exceedances.map((exc) => [
      exc.element_id,
      exc.type,
      exc.value,
      exc.limit,
      exc.location,
      exc.recommendation,
    ]);

    const csv = [
      headers.join(','),
      ...rows.map((row) => row.map((cell) => `"${cell}"`).join(',')),
    ].join('\n');

    const blob = new Blob([csv], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'exceedances.csv';
    a.click();
    window.URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Print/Download Report */}
      <Card>
        <CardHeader>
          <CardTitle>Analysis Report</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex items-center gap-4">
            <div className="flex-shrink-0 w-16 h-20 bg-muted rounded flex items-center justify-center">
              <FileText className="h-8 w-8 text-muted-foreground" />
            </div>
            <div className="flex-1">
              <p className="font-medium">Analysis Report</p>
              <p className="text-sm text-muted-foreground">
                Complete structural analysis with summary and recommendations
              </p>
            </div>
            <Button onClick={handlePrintReport} disabled={!analysisResult}>
              <Printer className="h-4 w-4 mr-2" />
              Print/Save PDF
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* CSV Export */}
      <Card>
        <CardHeader>
          <CardTitle>Export Data</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex items-center justify-between">
            <div>
              <p className="font-medium">Exceedances CSV</p>
              <p className="text-sm text-muted-foreground">
                Export all exceedances to a spreadsheet-compatible format
              </p>
            </div>
            <Button
              onClick={exportToCSV}
              disabled={!exceedances || exceedances.length === 0}
              variant="outline"
            >
              <Download className="h-4 w-4 mr-2" />
              Export CSV
            </Button>
          </div>
        </CardContent>
      </Card>

      {!reportUrl && (!exceedances || exceedances.length === 0) && (
        <div className="text-center py-12 text-muted-foreground">
          <FileText className="h-12 w-12 mx-auto mb-4 opacity-50" />
          <p>No reports available yet</p>
          <p className="text-sm mt-1">Run an analysis to generate reports</p>
        </div>
      )}
    </div>
  );
}
